name: Matriz lab
on: push

jobs:
    my-matrix:
        name: ${{matrix.node_version}} - ${{ matrix.os}}
        strategy:
            matrix:
                node_version: [14,16,18]
                os: [ubuntu-latest, ubuntu-24.04]
        runs-on: ${{ matrix.os }}
        steps:
            - name: Display node version
              run: echo "Hello ${{ github.run_number}}"

