name: Matriz lab
on: push

jobs:
    my-matrix:
        name: ${{matrix.node_version}}
        strategy:
            matrix:
                node_version: [14,16,18]
        runs-on: ubuntu-latest
        steps:
            - name: Display node version
              run: echo "Hello ${{ github.run_number}}"

