name: 06 - Contexts
run-name: "Context: ${{github.run_number}} | input_boolean: ${{inputs.input_boolean}} input_string: ${{inputs.input_string}} input_number: ${{inputs.input_number}}"
on:
    push:
    workflow_dispatch:
        inputs:
            input_boolean:
                type: boolean
                default: false
            input_string:
                type: string
                default: "My input - type: string"
            input_number:
                type: number
                default: 0
jobs:
    echo-data:
        runs-on: ubuntu-latest
        steps:
            - name: Display Information
              run: |
                echo "Event name: ${{github.event_name}}"
                echo "Ref: ${{github.ref}}"
                echo "SHA: ${{github.sha}}"
                echo "Actor: ${{github.actor}}"
                echo "workflow: ${{github.workflow}}"
                echo "Run ID: ${{github.run_id}}"
                echo "Run number: ${{github.run_number}}"
                echo "Env: ${{env}}"
                echo "Runner name: ${{runner.name}}"
                echo "Inputs: ${{inputs}}"
                echo "steps: ${{steps}}"
                echo "secrets: ${{secrets}}"
                echo "Job status: ${{job.status}}"
                echo "Job workflow_file_path: ${{job.workflow_file_path}}"
            - name: Retrieve Variable
              run: |
                 echo "Variable value: ${{vars.MY_VAR}}"
