name: 07 - Using Expressions
run-name: Expressions | DEBUG - <'ON' if debug input is true, 'OFF' otherwise>
on: 
    push:
    workflow_dispatch:
        inputs:
            debug_input:
                type: boolean
                default: false

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
            - name: "[Debug] Print start-up data"
              # if: ${{inputs.debug_input == true}}
              if: inputs.debug_input == true
              run: | 
                echo "Triggered by: ${{github.event_name}}"
                echo "Branch github.ref: ${{github.ref}}"
                echo "Branch GITHUB_REF: $GITHUB_REF"
                echo "Commit SHA: ${{github.sha}}"
                echo "Runner RUNNER_OS: $RUNNER_OS"
                echo "Runner runner.os: ${{runner.os}}"
                echo "Branch name: ${{github.ref_name}}"
            - name: "[debug] Print when triggered from main"
              # if: ${{inputs.debug_input == false && github.ref_name=='main'}}
              if: inputs.debug_input == false && github.ref_name=='Dev'
              run: echo "I was triggered from main"
            - name: Greeting
              run: echo "Great job!"
                




    

