name: 13 - Using Caching
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: 04-using-actions/react-app
    steps:
      - name: Checkout code
        run: actions/checkout@v4
      - name: Display info
        run: "Checkout executed"
