name: 17 - 2 - Custom Actions - JS
run-name: 17 - 2 - Custom Actions - JS- from ${{inputs.base-branch}} to ${{inputs.target-branch}} on ${{inputs.working-dir}}
on:
    workflow_dispatch:
        inputs:
            base-branch:
                type: string
                default: main
            target-branch:
                type: string
                default: update-dependencies
            working-dir:
                type: string
                default: app/react-app
            # debug:
            #     type: string
            #     default: 'false'
# env:            
#     gh-token: ${{secrets.GITHUB_TOKEN}}
#     # Retrieve value from secrets.GITHUB_TOKEN

jobs:
    dependency-update:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Check for dependency updates
              uses: ./.github/actions/js-dependency-update
              with:
                base-branch: ${{ inputs.base-branch }}
                target-branch: ${{ inputs.target-branch }}
                working-dir: ${{ inputs.working-dir}}
                                      

